# Generated by Django 4.2.1 on 2023-08-29 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employer_user_alter_profile_user'),
        ('analytics', '0003_remove_job_location_job_city_job_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.employer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_job', to='analytics.workform'),
        ),
        migrations.AlterField(
            model_name='job',
            name='markets',
            field=models.ManyToManyField(blank=True, null=True, to='analytics.market'),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(null=True, to='analytics.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_job', to='analytics.worktype'),
        ),
    ]
